<?php
/**
 * Created by PhpStorm.
 * @purpose 默认菜单配置文件
 * @Author: cbf
 * @Time: 2022/9/20 22:01
 */

return [
    0 => [
        'id' => 1,
        'title' => '工作空间',
        'icon' => 'layui-icon layui-icon-console',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 10,
                'title' => '控制后台',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/console/console1.html',
            ],
            1 => [
                'id' => 13,
                'title' => '数据分析',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/console/console2.html',
            ],
            2 => [
                'id' => 14,
                'title' => '百度一下',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'http://www.bing.com',
            ],
            3 => [
                'id' => 15,
                'title' => '主题预览',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/theme.html',
            ],
            4 => [
                'id' => 16,
                'title' => '酸爽翻倍',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/document/core.html',
            ],
        ],
    ],
    1 => [
        'id' => 'component',
        'title' => '常用组件',
        'icon' => 'layui-icon layui-icon-component',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 201,
                'title' => '基础组件',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 0,
                'children' => [
                    0 => [
                        'id' => 2011,
                        'title' => '功能按钮',
                        'icon' => 'layui-icon layui-icon-face-smile',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/button.html',
                    ],
                    1 => [
                        'id' => 2014,
                        'title' => '表单集合',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/form.html',
                    ],
                    2 => [
                        'id' => 2010,
                        'title' => '字体图标',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/icon.html',
                    ],
                    3 => [
                        'id' => 2012,
                        'title' => '多选下拉',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/select.html',
                    ],
                    4 => [
                        'id' => 2013,
                        'title' => '动态标签',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/tag.html',
                    ],
                ],
            ],
            1 => [
                'id' => 203,
                'title' => '进阶组件',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 0,
                'children' => [
                    0 => [
                        'id' => 2031,
                        'title' => '数据表格',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/table.html',
                    ],
                    1 => [
                        'id' => 2032,
                        'title' => '分布表单',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/step.html',
                    ],
                    2 => [
                        'id' => 2033,
                        'title' => '树形表格',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/treetable.html',
                    ],
                    3 => [
                        'id' => 2034,
                        'title' => '树状结构',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/dtree.html',
                    ],
                    4 => [
                        'id' => 2035,
                        'title' => '文本编辑',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/tinymce.html',
                    ],
                    5 => [
                        'id' => 2036,
                        'title' => '卡片组件',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/card.html',
                    ],
                ],
            ],
            2 => [
                'id' => 202,
                'title' => '弹层组件',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 0,
                'children' => [
                    0 => [
                        'id' => 2021,
                        'title' => '抽屉组件',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/drawer.html',
                    ],
                    1 => [
                        'id' => 2022,
                        'title' => '消息通知 (过时)',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/notice.html',
                    ],
                    2 => [
                        'id' => 2025,
                        'title' => '消息通知 (新增)',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/toast.html',
                    ],
                    3 => [
                        'id' => 2024,
                        'title' => '加载组件',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/loading.html',
                    ],
                    4 => [
                        'id' => 2023,
                        'title' => '弹层组件',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/popup.html',
                    ],
                ],
            ],
            3 => [
                'id' => 60331,
                'title' => '高级组件',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 0,
                'children' => [
                    0 => [
                        'id' => 60131,
                        'title' => '多选项卡',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/tab.html',
                    ],
                    1 => [
                        'id' => 60132,
                        'title' => '数据菜单',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/menu.html',
                    ],
                ],
            ],
            4 => [
                'id' => 204,
                'title' => '其他组件',
                'icon' => 'layui-icon layui-icon-console',
                'type' => 0,
                'children' => [
                    0 => [
                        'id' => 2041,
                        'title' => '哈希加密',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/encrypt.html',
                    ],
                    1 => [
                        'id' => 2042,
                        'title' => '图标选择',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/iconPicker.html',
                    ],
                    2 => [
                        'id' => 2043,
                        'title' => '省市级联',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/area.html',
                    ],
                    3 => [
                        'id' => 2044,
                        'title' => '数字滚动',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/count.html',
                    ],
                    4 => [
                        'id' => 2045,
                        'title' => '顶部返回',
                        'icon' => 'layui-icon layui-icon-face-cry',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/topBar.html',
                    ],
                    5 => [
                        'id' => 2046,
                        'title' => '水印组件',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/watermark.html',
                    ],
                    6 => [
                        'id' => 2047,
                        'title' => '全屏组件',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/fullscreen.html',
                    ],
                    7 => [
                        'id' => 2048,
                        'title' => '汽泡组件',
                        'type' => 1,
                        'openType' => '_iframe',
                        'href' => 'view/document/popover.html',
                    ],
                ],
            ],
        ],
    ],
    2 => [
        'id' => 'result',
        'title' => '结果页面',
        'icon' => 'layui-icon layui-icon-auz',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 'success',
                'title' => '成功',
                'icon' => 'layui-icon layui-icon-face-smile',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/result/success.html',
            ],
            1 => [
                'id' => 'failure',
                'title' => '失败',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/result/error.html',
            ],
        ],
    ],
    3 => [
        'id' => 'error',
        'title' => '错误页面',
        'icon' => 'layui-icon layui-icon-face-cry',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 403,
                'title' => '403',
                'icon' => 'layui-icon layui-icon-face-smile',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/error/403.html',
            ],
            1 => [
                'id' => 404,
                'title' => '404',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/error/404.html',
            ],
            2 => [
                'id' => 500,
                'title' => '500',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/error/500.html',
            ],
        ],
    ],
    4 => [
        'id' => 'system',
        'title' => '系统管理',
        'icon' => 'layui-icon layui-icon-set-fill',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 601,
                'title' => '用户管理',
                'icon' => 'layui-icon layui-icon-face-smile',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/user.html',
            ],
            1 => [
                'id' => 602,
                'title' => '角色管理',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/role.html',
            ],
            2 => [
                'id' => 603,
                'title' => '权限管理',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/power.html',
            ],
            3 => [
                'id' => 604,
                'title' => '部门管理',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/deptment.html',
            ],
            4 => [
                'id' => 605,
                'title' => '行为日志',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/log.html',
            ],
            5 => [
                'id' => 606,
                'title' => '数据字典',
                'icon' => 'layui-icon layui-icon-face-cry',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/dict.html',
            ],
        ],
    ],
    5 => [
        'id' => 'common',
        'title' => '常用页面',
        'icon' => 'layui-icon layui-icon-template-1',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 701,
                'title' => '登录页面',
                'icon' => 'layui-icon layui-icon-face-smile',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'login.html',
            ],
            1 => [
                'id' => 702,
                'title' => '空白页面',
                'icon' => 'layui-icon layui-icon-face-smile',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/system/space.html',
            ],
        ],
    ],
    6 => [
        'id' => 'echarts',
        'title' => '数据图表',
        'icon' => 'layui-icon layui-icon-chart',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 12121,
                'title' => '折线图',
                'icon' => 'layui-icon layui-icon-face-smile',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/echarts/line.html',
            ],
            1 => [
                'id' => 121212,
                'title' => '柱状图',
                'icon' => 'layui-icon layui-icon-face-smile',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'view/echarts/column.html',
            ],
        ],
    ],
    7 => [
        'id' => 'code',
        'title' => '开发工具',
        'icon' => 'layui-icon layui-icon-util',
        'type' => 0,
        'href' => '',
        'children' => [
            0 => [
                'id' => 801,
                'title' => '表单构建',
                'icon' => 'layui-icon layui-icon-util',
                'type' => 1,
                'openType' => '_iframe',
                'href' => 'component/code/index.html',
            ],
        ],
    ],
];